site_name: Vulkan Bits
nav:
  - Home: index.md
  - Device: device.md 
  - Swapchain: swapchain.md
  - About: about.md

theme: 
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - c
    - cpp